### ISSUE TITLE
Need links

### ISSUE THREAD

**Issue by omsenjalia** [corpnewt/CorpBot.py#109]
Hey sorry for making a issue but can I please have Support server or a link to invite the bot I just wanna check it out ty (I recommend giving both)

**Comment by corpnewt** [comment]
I don't have a support server for the bot - and the instance of the bot I personally host is barred from joining new servers due to discord bot verification.  If you just want to test the bot out, I have an instances running on reddit's /r/hackintosh sub's discord.  The join link for that is [here](https://discord.gg/u8V7N5C).

-CorpNewt

**Comment by omsenjalia** [comment]
I saw your reddit on your profile I also checked it out but I didn't find any links
