### ISSUE TITLE
Get/Set User Stats Issues

### ISSUE THREAD

**Issue by Baltire** [corpnewt/CorpBot.py#72]
Hello,

We are unable to set or get our global user stats, the format may be the root cause of this error, I'm getting the following for `settz`:

> Ignoring exception in command settz:
> Traceback (most recent call last):
>   File "\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "\Cogs\Time.py", line 52, in settz
>     self.settings.setGlobalUserStat(ctx.author, "TimeZone", tz_list[index]['Item'])
>   File "Cogs\Settings.py", line 734, in setGlobalUserStat
>     userList[str(user.id)][stat] = value
> **TypeError: list indices must be integers or slices, not str**

**Comment by corpnewt** [comment]
If your settings were initialized prior to [this commit](https://github.com/corpnewt/CorpBot.py/commit/500d0d1bf4baead7780f9ec2a4735f7278c25c11), then it makes sense that the `GlobalMembers` var was initialized incorrectly.  You could adjust the .json settings file to change `GlobalMembers` to a dict instead of a list and that should fix the issue.

Doing that via python would look something like this (untested, and off the top of my head):
```py
import json
s = json.load(open("Settings.json"))
if isinstance(s.get("GlobalMembers",{}), list):
    s["GlobalMembers"] = {}
json.dump(s,open("Settings","w"),indent=2)
```
The above code expects the current directory to be the bot's directory (`CorpBot.py` if you cloned the repo normally).

Hopefully that helps.

-CorpNewt

**Comment by Baltire** [comment]
I've cloned your latest repo from the rewrite branch and I just started using MongoDB - JSON may lower his performances. Your code above looks a bit weird so for a DB user.

**Comment by corpnewt** [comment]
The MongoDB implementation is not complete.  My main bot used json alone until I started the [redis branch](https://github.com/corpnewt/CorpBot.py/tree/redis).  You are correct, though, that the above code would not work for Mongo - only for json.  You should be able to adjust the `GlobalMembers` value in the db to change its type from a list to a dict which should bypass that error.

**Comment by Baltire** [comment]
Do you have any plans about that Mongo implemantation? If so, any ETA? Or Redis will be now always your priority?

**Comment by corpnewt** [comment]
I don't have any immediate plans to revise the Mongo implementation.  Redis has been my main focus of late.  At _some point_ in the future, I plan to add more db support - but that won't be until I finalize the redis branch (which is still a work in progress).

**Comment by Baltire** [comment]
Thanks for your answers :)
