### ISSUE TITLE
Links in Lists encoding characters.

### ISSUE THREAD

**Issue by im-not-a-dev** [corpnewt/CorpBot.py#91]
When adding either a hack or link to the bot in the following form, the bot will encode the trailing ticks in rawhack/rawlink.
> \```https://test.com```

Expected behaviour would be: 
> User: $addlink test \```https://test.com```
> Bot: test added to link list!
> User: $link test
> Bot: ```https://test.com```
> User: $rawlink test
> Bot: \```https://test.com```

Instead the observed behaviour is:
> User: $addlink test \```https://test.com```
> Bot: test added to link list!
> User: $link test
> Bot: ```https://test.com```
> User: $rawlink test
> Bot: \```https://test.com/%60%60%60

**Comment by corpnewt** [comment]
The bot doesn't encode them - escaping them makes discord treat the back ticks as part of the url. This is normal and expected behavior. If you want raw links within back ticks, separating them by newlines should help like so:

\`\`\`
http://test.com
\`\`\`

This should result in the same linked output, but without the rawlink including the back ticks as part of the url.

-CorpNewt
